#!/usr/bin/env bash
echo "This script will delete a bucket and all of its contents."

# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. /bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1
# https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html

aws s3api delete-bucket \
  --bucket "$BUCKET_NAME" \
  --region ca-central-1 \