#!/usr/bin/env bash
echo "This script will delete objects in a bucket."

# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. /bucket my-bucket-name."
    exit 1
fi

BUCKET_NAME=$1
# https://docs.aws.amazon.com/cli/latest/reference/s3/rm.html
aws s3 rm "s3://$BUCKET_NAME" --recursive --region ca-central-1
